Iter9 Use file as a storage
RED143/shorty pull request #12
Opened 2023-05-29 18:57 UTC by RED143

2023-05-31 23:40 UTC, s-shpak requested changes

2023-05-31 23:40 UTC, s-shpak commented on go.mod
Надо обновить с помощью `go mod tidy`

2023-05-31 23:40 UTC, s-shpak commented on internal/app/compress/compress.go
> +	w  http.ResponseWriter
Это поле можно встроить, чтобы не переопределять, например, `Header()`

2023-05-31 23:40 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		logger.Debug("failed to parse request body", "err", err)
Неожиданные ошибки лучше логировать на уровне Error

2023-05-31 23:40 UTC, s-shpak commented on internal/app/logger/logger.go
> +var sugar *zap.SugaredLogger
Глобальные переменные не нужны. Передавай логгер в те функции, в которых он используется явно (или через поле структуры)

2023-05-31 23:40 UTC, s-shpak commented on internal/app/logger/logger.go
> +		log.Fatalf("can't initialize logger: %v", err)
Не надо выходить из программы в глубине кода

2023-05-31 23:40 UTC, s-shpak commented on internal/app/logger/logger.go
> +func Info(msg string, fields ...interface{}) {
Зачем переопределять эту функцию? Используй логгер напрямую

2023-05-31 23:40 UTC, s-shpak commented on internal/app/server/server.go
> +	router.Post("/", logger.WithLogging(compress.CompressMiddleware(h.shortifyLink)))
Регистрируй middleware через `chi.Use`

2023-05-31 23:40 UTC, s-shpak commented on internal/app/storage/storage.go
> +type fileStorage struct {
Я бы не стал так делать: для работы с данными используй мапу, просто пусть этот сторедж параллельно сохраняет данные в файл. Чиать файл каждый раз, когда пользователь запрашивает длинную ссылку - дорого

2023-06-01 09:37 UTC, RED143 commented on internal/app/storage/storage.go
> +type fileStorage struct {
@s-shpak я понимал это (про быстродействие), но меня смущало, что у меня не будет единого источника правды(2 дублирующих хранилища), поэтому решил попробовать реализовать таким путем, чтобы можно было подменять сторадж без лишних затрат, т.е. на следующем шаге добавить бд, например. В любом случае я переписал

2023-06-01 09:57 UTC, RED143 commented on internal/app/compress/compress.go
> +	w  http.ResponseWriter
 сделал тоже самое для ридера

2023-06-01 11:33 UTC, RED143 commented on internal/app/compress/compress.go
> +	w  http.ResponseWriter
сс @s-shpak

2023-06-04 11:30 UTC, s-shpak requested changes

2023-06-04 11:30 UTC, s-shpak commented on internal/app/compress/compress.go
> +	w  http.ResponseWriter
Для этого надо поменять код `WriteHeader`:

```go
func (c *compressWriter) WriteHeader(statusCode int) {
	if statusCode < 300 {
		c.ResponseWriter.Header().Set("Content-Encoding", "gzip")
	}
	c.ResponseWriter.WriteHeader(statusCode)
}
```

Почитай как работате композиция в go

2023-06-04 11:30 UTC, s-shpak commented on internal/app/handlers/handlers_test.go
> +	storageMock, _ := storage.NewStorage("")
Ошибки надо проверять

2023-06-04 11:30 UTC, s-shpak commented on internal/app/logger/logger.go
> +type Logger = interface {
Лучше не объявлять совй интерфейс, а использовать ту структуру, которую предоставляет библиотека логгирования

2023-06-04 11:30 UTC, s-shpak commented on internal/app/logger/logger.go
> +		start := time.Now()
Таймер лучше стартовать перед вызовом хендлера

2023-06-04 11:30 UTC, s-shpak commented on internal/app/storage/storage.go
> +var linesCount = 0
Глобальные переменные не нужны

2023-06-04 11:30 UTC, s-shpak commented on internal/app/storage/storage.go
> +		return err
Ошибки из сторонних библиотек или пакетов нужно оборачивать

2023-06-04 18:03 UTC, RED143 commented on internal/app/storage/storage.go
> +var linesCount = 0
Я удалил всю логику с linesCount,  тк это по сути была просто имитация какого-то метода для генерации uuid, но она достаточно костыльная(след uuid это новый номер строки), все равно мы будем юзать id из базы. Если все таки uuid нужен, то я либо подключу какой-нибудь пакет, или напишу какую-то свою простую реализацию не связанную со строчками в файле

2023-06-04 20:27 UTC, s-shpak requested changes

2023-06-04 20:27 UTC, s-shpak commented on internal/app/logger/logger.go
> +type Logger = *zap.SugaredLogger
Нет смысла объявлять новый тип, используй непосредственно библиотечный

2023-06-04 20:27 UTC, s-shpak commented on internal/app/compress/compress.go
> +	w  http.ResponseWriter
Ты будешь править это в этом спринте?

2023-06-04 20:27 UTC, s-shpak commented on internal/app/storage/storage.go
> +var linesCount = 0
Подключи свою, связанную, логику, просто храни каунтер строк в объекте `Storage`, например: это не очень изяхное решение, но в контексте текущей реализации подойдет. Согласно ТЗ в файле должны быть айдишники на каждой строке

2023-06-05 16:31 UTC, RED143 commented on internal/app/compress/compress.go
> +	w  http.ResponseWriter
да, случайно не попало

2023-06-05 16:40 UTC, RED143 commented on internal/app/logger/logger.go
> +type Logger = *zap.SugaredLogger
поправил, идея была в том, что если поменяется либа, то менять придется только в одном месте

2023-06-05 17:37 UTC, s-shpak commented on internal/app/logger/logger.go
> +type Logger = *zap.SugaredLogger
Ничего страшного: это нормальный инстинкт, но для некоторых компонентов (логгера, например) это оверкилл. На 1-1 можем поговорить почему

2023-06-05 17:39 UTC, s-shpak approved these changes

2023-06-06 05:06 UTC, merged