Iter13 handle db conflicts
RED143/shorty pull request #16
Opened 2023-06-12 18:57 UTC by RED143

2023-06-17 16:37 UTC, s-shpak requested changes

2023-06-17 16:37 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +func ShortenLink(ctx context.Context, writer http.ResponseWriter, request *http.Request, cfg config.Config, str storage.Storage, logger *zap.SugaredLogger) {
Дабы не дуплицировать логику, я бы объединил эту функцию с `Shortify`

2023-06-17 16:37 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	if request.Method != http.MethodPost {
В принципе, т.к. ты используешь внешний роутер теперь, эти проверки можно убрать

2023-06-17 16:37 UTC, s-shpak commented on internal/app/storage/dbstorage/dbstorage.go
> +		return nil, err
Ошибки из сторонних библиотек лучше оборачивать

2023-06-17 16:37 UTC, s-shpak commented on internal/app/storage/dbstorage/dbstorage.go
> +	row := conn.QueryRowContext(context.TODO(), "SELECT url FROM links WHERE hash = $1", key)
Здесь стоит использовать контекст, который ты передаешь первым аргументом

2023-06-17 16:37 UTC, s-shpak commented on internal/app/storage/dbstorage/dbstorage.go
> +	fmt.Println("db storage batching!!!", urls)
deadcode

2023-06-17 16:37 UTC, s-shpak commented on internal/app/storage/dbstorage/dbstorage.go
> +	for _, url := range urls {
Сейчас это не батчинг, это запись данных в БД по очереди. В идеале, ты должен делать фиксированное количество запросов к БД (один, например), которое не должно зависеть от количества отправляемых данных. Для батчинга можно:
1. перейти на `pgx` вместо `db/sql`
2. формировать запрос самому
3. использовать библиотеку типа `sqlx` или `squirrel`

2023-06-17 16:37 UTC, s-shpak commented on internal/app/storage/filestorage/filestorage.go
> +	s.mu.Lock()
Если ты защищаешь этим мьютексом доступ к `links`, то лучше это делать после дорогих операций записи в файл, в тот момент когда ты дейтсвительно получаешь доступ к `links`

Я бы просто переиспользовал `mapstorage` здесь: filestorage может быть просто оберткой для `mapstorage`

2023-06-17 16:37 UTC, s-shpak commented on internal/app/storage/filestorage/filestorage.go
> +	return errors.New("there is no ping method for file storage")
Не надо выбрасывать ошибку: верни просто `nil`

2023-06-18 10:27 UTC, RED143 commented on internal/app/handlers/handlers.go
> +func ShortenLink(ctx context.Context, writer http.ResponseWriter, request *http.Request, cfg config.Config, str storage.Storage, logger *zap.SugaredLogger) {
Я немного встрял со способом определения какой конкретно у нас запрос(json или plain) и нашел только один рабочий способ через URI:
```go
isJSONRequest := request.RequestURI == "/api/shorten"
```
я пытался определять через content-type из реквеста, но тесты фейлятся на модуле компресии тк там приходит свой content-type. По идее должен быть более изящный способ

2023-06-18 11:12 UTC, RED143 commented on internal/app/storage/filestorage/filestorage.go
> +	s.mu.Lock()
я пока передвинул вызов, но хотел бы обсудить это на 1-1

2023-06-18 20:28 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +func ShortenLink(ctx context.Context, writer http.ResponseWriter, request *http.Request, cfg config.Config, str storage.Storage, logger *zap.SugaredLogger) {
А какой `content-type` приходит в тестах?

2023-06-18 20:40 UTC, s-shpak requested changes

2023-06-18 20:40 UTC, s-shpak commented on internal/app/storage/dbstorage/dbstorage.go
> +		values[index] = "('" + hash.Generate([]byte(url.OriginalURL)) + "', '" + url.OriginalURL + "')"
Это уже лучше, но теперь есть вероятность SQL-инъекции. Тебе надо приудмать, как вставлять данные, используя `($1, $2)` (это позволяет предотвратить инъекцию)

2023-06-18 20:40 UTC, s-shpak commented on internal/app/storage/dbstorage/dbstorage.go
> +	db *sql.DB
Соединение надо уметь закрывать. И надо делать это в случае завершения программы

2023-06-19 04:09 UTC, RED143 commented on internal/app/handlers/handlers.go
> +func ShortenLink(ctx context.Context, writer http.ResponseWriter, request *http.Request, cfg config.Config, str storage.Storage, logger *zap.SugaredLogger) {
@s-shpak `application/x-gzip`

2023-06-19 04:09 UTC, RED143 commented on internal/app/handlers/handlers.go
> +func ShortenLink(ctx context.Context, writer http.ResponseWriter, request *http.Request, cfg config.Config, str storage.Storage, logger *zap.SugaredLogger) {
@s-shpak `application/x-gzip`

2023-06-19 08:41 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +func ShortenLink(ctx context.Context, writer http.ResponseWriter, request *http.Request, cfg config.Config, str storage.Storage, logger *zap.SugaredLogger) {
(⊙.⊙)

2023-06-19 08:44 UTC, s-shpak requested changes

2023-06-19 08:44 UTC, s-shpak commented on internal/app/server/server.go
> +		if dbError := s.Close(); dbError != nil {
Несколько неправильная логика: соединение к БД должно закрываться в любом случае

2023-06-19 17:07 UTC, s-shpak approved these changes

2023-06-20 06:24 UTC, merged