Iter15
RED143/shorty pull request #18
Opened 2023-06-22 08:53 UTC by RED143

2023-06-29 18:49 UTC, s-shpak requested changes

2023-06-29 18:49 UTC, s-shpak commented on internal/app/authorization/authorization.go
> +const secret = "shouldBeSavedInEnvFile"
Да, согласен. Хоть этого и нет в ТЗ, давай прикрутим возможность передавать при старте сервера

2023-06-29 18:49 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	userID := requestContext.Value(authorization.ContextKey("userID"))
Подтяни ключ из того же пакета, где ты его добавляешь в контекст

2023-06-29 18:49 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	} else {
Старайся использовать меньше `else`, это, как правило, делает код более читаемым

2023-06-29 18:49 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	go func() {
1. К БД может улетать очень большое количество запросов, которое может положить БД, как этого можно избежать (используя конфигурацию хендлера БД)?
2. Это необязательно, но если будут силы, подумай, как сделать graceful shutdown в этом случае?

2023-06-29 18:49 UTC, s-shpak commented on internal/app/storage/dbstorage/dbstorage.go
> +		condition += sep + " (user_id = $1 AND short_url = $" + strconv.Itoa(index+2) + ")"
Посмотри как это можно улучшить: https://www.opsdash.com/blog/postgres-arrays-golang.html

2023-06-29 18:49 UTC, s-shpak commented on internal/app/storage/filestorage/filestorage.go
> +	return nil, nil
Эту логику стоит реализовать

2023-06-29 18:49 UTC, s-shpak commented on internal/app/storage/mapstorage/mapstorage.go
> +	return nil, nil
Эту логику стоит реализовать

2023-06-30 11:13 UTC, RED143 commented on internal/app/handlers/handlers.go
> +	go func() {
1. настроить пул соединений для запросов к бд? например установить максимальное количество соединений и лимитировать по времени каждое соединение?

cc @s-shpak

2023-06-30 11:19 UTC, RED143 commented on internal/app/handlers/handlers.go
> +	go func() {
или имеется ввиду какая-то логика на уровне горутин? например паттерн семафор, чтобы ограничить количество запросов к бд?

2023-06-30 12:30 UTC, s-shpak commented on internal/app/authorization/authorization.go
> +const UserIDContextKey = ContextKey("userID")
В целом это работает. Можно еще использовать `iota` для определения ключей, это еще надежнее: https://forum.golangbridge.org/t/the-way-to-set-a-context-key-and-value/16311/2. Это необязательно, если не будешь это делать, просто зарезолвь коммент

2023-06-30 12:30 UTC, s-shpak commented on internal/app/authorization/authorization.go
> +type ContextKey string
Этот тип необязательно делать экспортируемым. Когда ты сделаешь его неэкспортируемым, один из тестов сломается, кстати

2023-06-30 12:30 UTC, s-shpak commented on internal/app/storage/mapstorage/mapstorage.go
> +	var UserUrls []models.UserURLs
Переменные не называют с большой буквы

2023-06-30 12:30 UTC, s-shpak commented on internal/app/storage/mapstorage/mapstorage.go
> +	return nil
Это тоже надо заимплементить

2023-06-30 12:30 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	go func() {
В данном случае достаточно будет ограничить количество соединений к БД на уровне пула

2023-06-30 12:31 UTC, s-shpak requested changes

2023-06-30 12:31 UTC, s-shpak commented on .golangci-lint.yml
>  # Source: pangoptic/templates/golangci-base.yml.tpl
Забыл выпилить это из репозитория, убери эту строку, пожалуйста

2023-07-02 11:53 UTC, s-shpak approved these changes

2023-07-02 14:04 UTC, merged