Iter5 Use env variables
RED143/shorty pull request #8
Opened 2023-05-06 14:13 UTC by RED143

Use env variables

2023-05-09 15:53 UTC, s-shpak requested changes

2023-05-09 15:53 UTC, s-shpak commented on internal/app/config/config.go
> +var Port = 8080
Этот объект необязательно делать экспортируемым

2023-05-09 15:53 UTC, s-shpak commented on internal/app/config/config.go
> +var Host = "localhost"
Этот объект необязательно делать экспортируемым

2023-05-09 15:53 UTC, s-shpak commented on internal/app/config/config.go
> +var BaseAddress = "localhost:8080"
Старайся по умолчанию не использовать "глобальные" переменные: это усложняет понимание кода и его тестирование, но не приносит никакой выгоды. Хорошей идеей было бы возвращать объект с параметрами конфигурации из `InitConfig` (переименовав его в `GetConfig`) и далее передавать конфигурацию аргументами

2023-05-09 15:53 UTC, s-shpak commented on internal/app/config/config.go
> +var Scheme = "http://"
Это лучше сделать не переменной, а константой (при помощи const)

2023-05-09 15:53 UTC, s-shpak commented on internal/app/config/config.go
> +		return "", 0, errors.New("invalid parsing url")
Оригинальные ошибки лучше тоже прокидывать наверх, чтобы сохранить информацию о причине возникновения ошибки: `fmt.Errorf("failed to split host and port in \"%s\": %w", s, err)`

2023-05-09 15:53 UTC, s-shpak commented on internal/app/config/config.go
> +		return "", 0, errors.New("invalid port")
1. К предыдущему комментарию: в сообщение об ошибке стоит включать информацию об аргументах, при передаче которых функция выкинула ошибку (это не стоит делать, когда аргументы могут нести конфиденциальную информацию, но в этом случае это вполне оправдано): `fmt.Errorf("failed to parse the port %s: %w", port, err)`
2. Стоит ли вообще парсить порт, если потом ты преобразуешь его обратно в строку? Для дополнительной проверки - может быть, хотя, если порт невалиден, ты не сможешь запустить свой сервер. Потому этот парсинг может быть избыточным

2023-05-09 15:53 UTC, s-shpak commented on internal/app/config/config.go
> +	flag.StringVar(&BaseAddress, "b", defaultAddress, "set a base address")
Переменная окружения должна иметь более высокий приоритет, чем флаг

2023-05-09 15:53 UTC, s-shpak commented on internal/app/server/server.go
> +		panic(err)
Это касается обработки всех ошибок в коде. Обычно в Go критические ошибки (которые не позволяют продолжить выполнение программы) возвращаются из функции и доходят до самого верхнего уровня (до функции main или, если речь идет об отдельной горутине, до функции которая была в ней запущена), где они логируются, и программа завершается.


Не стоит выходить из программы (паниковать или вызывать os.Exit(1)) где-то в глубине логики:
- Код сложнее читать, лучше, когда понятно, где именно точка выхода
- Не получится завершить сторонние процессы штатным образом, что может привести к проблемам

2023-05-09 15:53 UTC, s-shpak commented on internal/app/hash/hash.go
> +func Generate(data []byte) string {
На подумать: есть ли какие-либо минусы у данного подода к сокращению ссылки?

2023-05-09 15:53 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +func ShortifyHandler(writer http.ResponseWriter, request *http.Request) {
Т.к. эта функция уже находится в пакете `handlers`, суффикс `Handler` кажется избыточным

2023-05-09 15:53 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	body, _ := io.ReadAll(request.Body)
Ошибки надо проверять

2023-05-09 15:53 UTC, s-shpak commented on go.mod
> +go 1.19
Стоит бампнуть Go до `1.20`

2023-05-09 15:53 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	response := config.BaseAddress + "/" + hashString
Для получения полного пути используй [JoinPath](https://pkg.go.dev/net/url#JoinPath)

2023-05-09 15:53 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		response = config.Scheme + response
См. преыдущий комментарий

2023-05-09 15:53 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	writer.Write([]byte(response))
Как ты думаешь, как обработать ситуацию, при которой `Write` вернет ошибку?

2023-05-09 15:53 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	hash := chi.URLParam(request, "hash")
Если мы заменим роутер, то нам придется менять и этот код. Желательно этого избежать

2023-05-09 15:53 UTC, s-shpak commented on internal/app/storage/storage.go
> +var storage = make(map[string]string)
Что произойдет, если сервер получит несколько запросов на запись/чтение? Как этого избежать?

2023-05-11 20:33 UTC, RED143 commented on internal/app/storage/storage.go
> +var storage = make(map[string]string)
наверное произойдет какой-то рассинхрон в дате. Я прочитал что в go map не защищён для доступа из нескольких потоков и надо либо имплементировать защиту самому, либо использовать специальный тип. Я использовал новый тип.

2023-05-11 20:37 UTC, RED143 commented on internal/app/config/config.go
> +var BaseAddress = "localhost:8080"
Пришлось вынести логику с флагами в отдельный метод, тк его нельзя вызвать дважды как я понял.

2023-05-11 20:40 UTC, RED143 commented on internal/app/config/config.go
> +		return "", 0, errors.New("invalid port")
1. теперь этих ошибок нет(смотри следующий пункт). Но посыл я понял
2. Я почему-то подумал что порт тоже надо хранить, по итогу я выкинул всю логику с портом. Что очень сильно упростило все.

2023-05-11 20:45 UTC, RED143 commented on internal/app/hash/hash.go
> +func Generate(data []byte) string {
Главный минус, что это не надежный способ и есть шанс коллизии. Можно дописать логику чтобы делать этот ключ дейстительно уникальным. Либо использовать base62 преобразование на идентификаторе(из базы данных например). Если я правильно понял, как это должно работать.

2023-05-12 03:48 UTC, RED143 commented on internal/app/handlers/handlers.go
> +	writer.Write([]byte(response))
Вернуть ошибку из метода Write и обработать в if'e ниже. Но я не знаю как это проверить, т.к. не знаю как вызвать ошибку намеренно во write. И еще я посмотрел, что можно чтобы мой роут handler возвращал error'ы,
потом его обернуть в какой-то логгер. Как это могло выглядеть в коде:
```go
 // handlers package
func Shortify(writer http.ResponseWriter, request *http.Request) error { }

// server package
router.Post("/", logRouteError(handlers.Shortify))
```

Гдe logRouteError вернет переданную функцию, если ошибок нет. Это правильно?

2023-05-12 04:00 UTC, RED143 commented on internal/app/handlers/handlers.go
> +	hash := chi.URLParam(request, "hash")
я добавил helper функцию для получения id из route, чтобы инкапсулировать в себе эту логику. Или не нужно использовать метод  из chi и написать какую-то свою имплементацию?

2023-05-12 04:00 UTC, RED143 commented on internal/app/config/config.go
> +var BaseAddress = "localhost:8080"
@s-shpak

2023-05-12 04:01 UTC, RED143 commented on internal/app/handlers/handlers.go
> +	writer.Write([]byte(response))
@s-shpak

2023-05-12 04:01 UTC, RED143 commented on internal/app/handlers/handlers.go
> +	hash := chi.URLParam(request, "hash")
@s-shpak

2023-05-12 04:01 UTC, RED143 commented on internal/app/storage/storage.go
> +var storage = make(map[string]string)
@s-shpak

2023-05-12 13:12 UTC, s-shpak requested changes

2023-05-12 13:12 UTC, s-shpak commented on cmd/shortener/main.go
> +		panic(err)
Не стоит паниковать, лучше вывести сообщение об ошибке и завершиться штатно, но с ненулевым кодом, см. `log.Fatal`

2023-05-12 13:12 UTC, s-shpak commented on internal/app/config/config.go
> +var cfg = config{}
Я бы обошелся без глобальной переменной: почему бы не возвращать конфиг из `GetConfig` где-то на верхнем уровне, а дальше прокидывать эту конифгурацию в каждый модуль в отдельности?

2023-05-12 13:12 UTC, s-shpak commented on internal/app/config/config.go
> +	flag.StringVar(&cfg.ServerAddress, "a", "localhost:8080", "set a server address")
Последний аргумент - опсание назнаение флага, т.е. вместо `set a server address` лучше использовать просто `server address`

2023-05-12 13:12 UTC, s-shpak commented on internal/app/config/config.go
> +	envServerAddress := os.Getenv("SERVER_ADDRESS")
Стилистическое (т.е. необязательное): я бы обернул это присвоение в `if` (как и следующее)

2023-05-12 13:12 UTC, s-shpak commented on internal/app/config/config.go
> +func ParseFlags() {
Кажется, что эта функция не должна быть экспортируемой: пользователю конфигурации неважно, как именно конфигурация получается, потому не он должен запрашивать парсинг флагов

2023-05-12 13:12 UTC, s-shpak commented on internal/app/config/config.go
> +var BaseAddress = "localhost:8080"
Я прокомментировал это в новом ревью. Как правило, получение кофнигурации в программе происходит один раз - при запуске. Потому можно ограничиться парсингом флагов один раз (когда пользователь запрашивает `GetConfig`).  принципе, можно использвать синглтон, чтобы гарантировать, что флаги не будут парситься несколько раз, но я бы не стал этим заморачиваться

2023-05-12 13:12 UTC, s-shpak commented on internal/app/storage/storage.go
> +var storage = sync.Map{}
я бы не стал сейчас использовать `sync.Map`:
1. В будуещем придется преходить на обычную мапу (т.к. с этим будут связаны инкременты)
2. `sync.Map` стоит использовать в определенных случаях, когда есть проблемы с эффективностью выполнения кода. Этот use-case к ним не относится.

Я бы предложил воспользоваться обычной мапой с мьютексом, но мьютекс опционален, т.к. мы его не проходили. Если чувствуешь в себе силы, то попробуй его использовать, если нет, то пока оставим в стороне проблемы с конкурентным доступом

2023-05-12 13:12 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	hash := chi.URLParam(request, "hash")
Я бы сделал немного по-другому: ты можешь определить функцию-хендлер в пакете `server`, которая будет вызывать `Shortify` (и другие функции с бизнес-логикой), передавая туда параметры из запроса. Так на имплементацию роутера мы будем ссылаться из одного пакета

2023-05-12 13:12 UTC, s-shpak commented on internal/app/util/util.go
> +func GetRouteID(request *http.Request, key string) string {
См. комментарий к пердыдущему ревью

2023-05-12 13:12 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	writer.Write([]byte(response))
1.Пока достаточно будет залогировать эту ошибку, тестировать это необязательно (можно сделать через моки, но это означает много усилий для проверки довольно экзотической и редкой ситуации)
2. Да, хорошая идея, это т.н. middleware. Мы будем говорить о них дальше в курсе, пока я бы не стал с этим разбираться

2023-05-12 13:12 UTC, s-shpak commented on internal/app/handlers/handlers_test.go
> +	for _, tc := range tests {
Я рекоммендую привыкнуть переопределять переменные из цикла внутри этого цикла для тестов (в данном случае `tc := tc`). Это особенно важно для тестов, т.к. тесты часто запускаются параллельно, а в этом случае возможны проблемы: https://eli.thegreenplace.net/2019/go-internals-capturing-loop-variables-in-closures/

2023-05-12 13:17 UTC, s-shpak commented on internal/app/hash/hash.go
> +func Generate(data []byte) string {
Про коллизии верно, более того, в случае с `md5` и использовании первых 7 символов они начнут встречаться довольно быстро (но, конечно, это зависит от нагрузки на сервис). Кроме того пользователи, которые сокращают одну и ту же ссылку будут получать один и тот же результат, что обычно не желательно.

Подход с идентификатором возможен, но он означает, что пользователь может угадать, какие короткие ссылки будут генерироваться на новые запросы (если идентификатор серийный), что может быть неправильно с т.з. безопасности сервиса. Если БД генерирует уникальные ID, то там тоже возникают проблемы.

Вобщем, это нетривиальный вопрос, а единого правильного ответа, как всегда, нет :(

2023-05-14 07:22 UTC, RED143 commented on internal/app/storage/storage.go
> +var storage = sync.Map{}
@s-shpak попробовал с mutex

2023-05-14 07:25 UTC, RED143 commented on internal/app/util/util.go
> +func GetRouteID(request *http.Request, key string) string {
@s-shpak я добавил handler'ы к server пакеты. Смущает немного что для каждого роута пришлось написать разные хэндлеры потому что каждый handler из handler package требует разных параметров. Для одного нужен  hash, а для второго конфиг

2023-05-15 12:42 UTC, s-shpak requested changes

2023-05-15 12:42 UTC, s-shpak commented on cmd/shortener/main.go
> +	err := server.Start()
Здесь `err` лучше обернуть в `if`

2023-05-15 12:42 UTC, s-shpak commented on internal/app/storage/storage.go
> +type storage struct {
`storage` лучше сделать экспортируемым. `GetValue` и `SetValue` необходимо сделать его методами (я бы назвал их `Get` и `Put`). Мьютекс должет защищать оба метода

2023-05-15 12:42 UTC, s-shpak commented on internal/app/storage/storage.go
> +func SetValue(key, value string) {
Эта функция станет не нужна после добавления метода и экспортирования `storage`

2023-05-15 12:42 UTC, s-shpak commented on internal/app/storage/storage.go
> +func GetValue(key string) (string, bool) {
Эта функция станет не нужна после добавления метода и экспортирования `storage`

2023-05-16 21:58 UTC, s-shpak requested changes

2023-05-16 21:58 UTC, s-shpak commented on cmd/shortener/main.go
> +	err := server.Start()
я имел в виду это:

```suggestion
	if err := server.Start(); err != nil {
	...
	}
```

2023-05-16 21:58 UTC, s-shpak commented on cmd/shortener/main.go
> +		log.Fatal("Closing with errorL", err)
```suggestion
		log.Fatalf("closing with error: %v", err)
```

2023-05-16 21:58 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(writer, "Only POST requests are allowed", http.StatusBadRequest)
здесь надо выйти из хендлера

2023-05-16 21:58 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(writer, "Failed to parse request body", http.StatusInternalServerError)
1. здесь надо выйти из хендлера
2. в случае `InternalServerError` не надо отправлять пользователю причину ошибки, достаточно обойтись сообщением `Internal server error`. Но ее стоит залогировать

2023-05-16 21:58 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(writer, "URL should be provided", http.StatusBadRequest)
здесь надо выйти из хендлера

2023-05-16 21:58 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(writer, "Failed to generate path", http.StatusInternalServerError)
1. здесь надо выйти из хендлера
2. в случае `InternalServerError` не надо отправлять пользователю причину ошибки, достаточно обойтись сообщением `Internal server error`. Но ее стоит залогировать

2023-05-16 21:58 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(writer, "Failed to write response", http.StatusInternalServerError)
1. здесь надо выйти из хендлера
2. в случае `InternalServerError` не надо отправлять пользователю причину ошибки, достаточно обойтись сообщением `Internal server error`. Но ее стоит залогировать

2023-05-16 21:58 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(writer, "Only GET requests are allowed", http.StatusBadRequest)
здесь надо выйти из хендлера

2023-05-16 21:58 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(writer, "Link not found", http.StatusBadRequest)
здесь надо выйти из хендлера

2023-05-16 21:58 UTC, s-shpak commented on internal/app/server/server.go
> +	router.Post("/", shortifyHandler(cfg))
круто, ты разобрался с замыканиями! :) И мне нравится, как ты организовал код роутера

2023-05-16 21:58 UTC, s-shpak commented on internal/app/storage/storage.go
> +type storage struct {
этот тип вместе с конструктором должен быть экспортируемым

2023-05-16 21:58 UTC, s-shpak commented on internal/app/storage/storage.go
> +var Storage = storage{
не стоит создавать глобальную переменную. Объяви конструктор `NewStorage`, и передавай проинициализированный объект в хендлер. Это можно сделать через аргумент, как ты делаешь сейчас с конфигруацией, но потом это придется править. А можно создавать новый объект и помещать `Storage` в его поле, а хендлер сделать методом (так сделать лучше, если чувтсвуешь в себе силы)

2023-05-17 06:08 UTC, RED143 commented on internal/app/storage/storage.go
> +var Storage = storage{
сделал первым способом, тк не очень понял что надо сделать во втором

2023-05-17 06:23 UTC, RED143 commented on internal/app/storage/storage.go
> +func NewStorage() *Storage {
я получал warning'и, когда пытался использовать значение storage в handlers без указателя:
`'Shortify' passes a lock by the value: type 'storage.Storage' contains 'sync.Mutex' which is 'sync.Locker' `. Поэтому я передал указатеть. Делал это по наитию не знаю насколько это правильно

сс @s-shpak

2023-05-17 07:52 UTC, s-shpak commented on internal/app/storage/storage.go
> +var Storage = storage{
Ок, перепишем на следующей итерации (не забудь спросить меня на one-on-one, если хочешь, потому что я могу забыть :( )

2023-05-17 07:54 UTC, s-shpak commented on internal/app/storage/storage.go
> +func NewStorage() *Storage {
Все почти верно, но лучше мьютекс тоже обяъвить указателем, и проиницализировать его в конструкторе:

```go
&Storage{
    links: map[string]string{},
    mu: &sync.Mutex{}
}
```

2023-05-17 07:57 UTC, s-shpak requested changes

2023-05-17 07:57 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		log.Println("failed to parse request body")
В Go принято логировать и саму ошибку, чтобы информация о причине не терялась:

```suggestion
		log.Printf("failed to parse request body: %v", err)
```

2023-05-17 07:57 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		log.Println("failed to generate path")
См. выше

2023-05-17 07:57 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		log.Println("failed to write response")
См. выше

2023-05-17 08:25 UTC, s-shpak approved these changes
LGTM!

2023-05-19 03:26 UTC, merged